version: '3.8'

services:
  postgres:
    container_name: bank_exchange
    image: postgres
    environment:
      POSTGRES_DB: bank_exchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"