spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/bank_exchange
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 20000
          central-bank-api:
            url: https://www.ecb.europa.eu
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs