spring:
  application:
    name: bank
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/bank_exchange
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 20000
          central-bank-api:
            url: https://www.ecb.europa.eu
  graphql:
    cors:
      allow-credentials: true
      max-age: 3600
      exposed-headers: '*'
      allowed-headers: '*'
      allowed-methods: '*'
      allowed-origins:
        - http://localhost:4200
      allowed-origin-patterns: /**

springdoc:
  swagger-ui:
    path: /v1/swagger-ui/index.html
  api-docs:
    path: /v1/swagger-ui/api-docs
  securitySchemeName: bearerAuth
  securityScheme: bearer
  bearerFormat: JWT
exchange:
  cron: 0 0 17 ? * *
jwt:
  secret: The sun has hidden behind the clouds, but the stars still shine in the heavens.
  token:
    validity: 120000
decimal:
  format: 0.000
  scale: 10